const APP = {
  DASHBOARD: {
    GET_LIST: 'VIEWS:CHARACTERS:GET_LIST',
    LIST_RECEIVING: 'VIEWS:CHARACTERS:LIST_RECEIVING',
    LIST_RECEIVING_ERROR: 'VIEWS:CHARACTERS:LIST_RECEIVING_ERROR',
    LIST_RECEIVED: 'VIEWS:CHARACTERS:LIST_RECEIVED',
    SET_LIST_FILTER: 'VIEWS:CHARACTERS:SET_LIST_FILTER',
  },
};

export default APP;
